name: Release Workflow

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v0.1.0, v0.2.0, etc.

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      - name: Build Linux binary
        run: |
          mkdir -p binaries/linux
          GOOS=linux GOARCH=amd64 go build -o binaries/linux/seqcraft-linux cmd/app/main.go

      - name: Build macOS binary
        run: |
          mkdir -p binaries/macOs
          GOOS=darwin GOARCH=amd64 go build -o binaries/macOs/seqcraft-macos cmd/app/main.go

      - name: Build Windows binary
        run: |
          mkdir -p binaries/windows
          GOOS=windows GOARCH=amd64 go build -o binaries/windows/seqcraft.exe cmd/app/main.go

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: binaries/**

  create-release:
    runs-on: ubuntu-latest
    needs: build-binaries
    if: github.actor == 'joushvak17'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: ./binaries

      - name: Rename binaries for release
        run: |
          mv ./binaries/linux/seqcraft-linux ./binaries/linux/seqcraft
          mv ./binaries/macOs/seqcraft-macos ./binaries/macOs/seqcraft

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
            - Linux: binaries/linux/seqcraft
            - macOS: binaries/macOs/seqcraft
            - Windows: binaries/windows/seqcraft.exe
          files: |
            binaries/linux/seqcraft
            binaries/macOs/seqcraft
            binaries/windows/seqcraft.exe